version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - apt-get update
      - apt-get install -y chromium-browser
      - npm ci

  build:
    commands:
      - npx ng test --no-watch --no-progress --browsers=ChromeHeadlessCI
