version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - yum update -y
      - yum install -y chromium
      - npm ci

  build:
    commands:
      - npx ng test --no-watch --no-progress --browsers=ChromeHeadlessCI
